name: Build WASM with Emscripten

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.63
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix git dubious ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Create output folder
        run: mkdir -p public/wasm

      - name: Compile with emcc
        run: |
          emcc src/cpp_core/main.cpp \
            -Isrc/cpp_core \
            -O3 \
            -std=c++17 \
            -s WASM=1 \
            -s ALLOW_MEMORY_GROWTH=1 \
            -s EXPORTED_RUNTIME_METHODS='["cwrap", "ccall", "UTF8ToString", "stringToUTF8"]' \
            -s EXPORT_ES6=1 \
            -s MODULARIZE=1 \
            -s EXPORT_NAME="DevToolsCoreModule" \
            -o public/wasm/devtools_core.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: public/wasm/

      - name: Auto commit WASM to repo
        uses: stefanzweifel/git-auto-commit-action@v6
